### ISSUE TITLE
Applicability of this library?

### ISSUE THREAD

**Issue by aschrijver** [go-ap/jsonld#1]
If this library is not dependent on other AP repo's and can be used for self-contained JSON-LD processing, then it has wider applicability, e.g. in the [Solid](https://solidproject.org) project. And I might also be interested to include on [delightful-linked-data](https://codeberg.org/teaserbot-labs/delightful-linked-data), which I just launched (part of [delightful](https://codeberg.org/teaserbot-labs/delightful) project).

I strongly encourage adding some Github topics to the repo, like 'json-ld' and 'linked-data' for findability.

**Comment by mariusor** [comment]
Hi @aschrijver, thank you for your interest.

This package is in the go-ap org, because I created it as a workaround for some issues I had with existing json-ld packages in the Go ecosystem. So I was forced to create something that was closer to my needs, but at the same time this is a hacky implementation that doesn't really have anything to do with JsonLD except the name.

I would advise you to not use it, as I am not offering any guarantees for how long I'll keep maintaining it. I feel like I know the domain problem enough to contribute to other projects the bits that interest me and then discard this one.

**Comment by aschrijver** [comment]
Thank you for the update!
